Create Spacecraft Sat;
Sat.DateFormat = UTCGregorian;
Sat.Epoch = '01 Jan 2025 12:00:00.000';
Sat.CoordinateSystem = EarthMJ2000Eq;
Sat.DisplayStateType = Keplerian;
Sat.SMA = 6790;
Sat.ECC = 0.001;
Sat.INC = 51.6;
Sat.RAAN = 0;
Sat.AOP = 0;
Sat.TA = 0;

Create ForceModel FM;
FM.CentralBody = Earth;
FM.PrimaryBodies = {Earth};

Create Propagator Prop;
Prop.FM = FM;

Create ReportFile rf;
rf.Filename = 'out.report';
rf.Add = {Sat.Earth.Latitude, Sat.Earth.Longitude};

BeginMissionSequence;
Propagate Prop(Sat) {Sat.ElapsedSecs = 5400};
Report rf Sat.Earth.Latitude Sat.Earth.Longitude;
