Create Spacecraft Sat;
Sat.DateFormat = UTCGregorian;
Sat.Epoch = '01 Jan 2025 12:00:00.000';
Sat.CoordinateSystem = EarthMJ2000Eq;
Sat.DisplayStateType = Keplerian;
Sat.SMA = 6878;
Sat.ECC = 0;
Sat.INC = 28.5;
Sat.RAAN = 0;
Sat.AOP = 0;
Sat.TA = 0;

Create ForceModel FM;
FM.CentralBody = Earth;
FM.PrimaryBodies = {Earth};

Create Propagator Prop;
Prop.FM = FM;

Create EphemerisFile ef;
ef.Spacecraft = Sat;
ef.FileFormat = CCSDS-OEM;
ef.Filename = 'sat.oem';

BeginMissionSequence;
Propagate Prop(Sat) {Sat.ElapsedSecs = 3600};
