Create Spacecraft Sat;
Sat.DateFormat = UTCGregorian;
Sat.Epoch = '01 Jan 2025 12:00:00.000';
Sat.CoordinateSystem = EarthMJ2000Eq;
Sat.DisplayStateType = Keplerian;
Sat.SMA = 6878;
Sat.ECC = 0;
Sat.INC = 28.5;
Sat.RAAN = 0;
Sat.AOP = 0;
Sat.TA = 0;

Create ForceModel FM;
FM.CentralBody = Earth;
FM.PrimaryBodies = {Earth};

Create Propagator Prop;
Prop.FM = FM;

Create ImpulsiveBurn dv;
dv.Axes = VNB;
dv.Element1 = -0.2;

BeginMissionSequence;
Maneuver dv(Sat);
Propagate Prop(Sat) {Sat.Periapsis};
