Create Spacecraft Sat;
Sat.DateFormat = UTCGregorian;
Sat.Epoch = '01 Jan 2025 12:00:00.000';
Sat.CoordinateSystem = EarthMJ2000Eq;
Sat.DisplayStateType = Keplerian;
Sat.SMA = 6878;
Sat.ECC = 0;
Sat.INC = 28.5;
Sat.RAAN = 0;
Sat.AOP = 0;
Sat.TA = 0;

Create ForceModel FM;
FM.CentralBody = Earth;
FM.PrimaryBodies = {Earth};

Create Propagator Prop;
Prop.FM = FM;

Create ImpulsiveBurn dv;
dv.Axes = VNB;

Create DifferentialCorrector DC;

Create ReportFile rf;
rf.Filename = 'out.report';
rf.Add = {Sat.Earth.RMAG};

BeginMissionSequence;
Target DC;
   Vary DC(dv.Element1 = 0.1, {Perturbation = 1e-4, Lower = 0, Upper = 1.0, MaxStep = 0.2});
   Maneuver dv(Sat);
   Propagate Prop(Sat) {Sat.Apoapsis};
   Achieve DC(Sat.Earth.RMAG = 8000, {Tolerance = 0.1});
EndTarget;
Report rf Sat.Earth.RMAG;
